/* GENERATED by scripts/gen-numbers.mjs — do not edit by hand.
 * Regenerate with: npm run gen:numbers (also runs before dev and build).
 *
 * Numbers for widget TSX. Never write "… from Theorem 4.6" as a string:
 *   import { num, ref } from "../numbers.generated";
 *   `… from ${ref("theorem:4.6")}`   -> "… from Theorem 4.6"
 *   num("eq:5.107")                    -> "5.107"
 * Keys are <directive>:<id> (theorem:, definition:, …), eq:<id>, sec:<id>.
 * An unknown key is a type error, not a silent typo.
 */
export type NumKey =
  | "definition:4.6"
  | "eq:4.12"
  | "eq:two-step"
  | "example:scaling-twice"
  | "sec:4.6"
  | "sec:4.6.1"
  | "sec:scaling-maps"
  | "sec:why-counted";

/** [number, reference text] per key. */
export const NUMBERS: Record<NumKey, readonly [string, string]> = {
  "definition:4.6": ["4.6", "Definition 4.6"],
  "eq:4.12": ["4.12", "(4.12)"],
  "eq:two-step": ["4.6.1", "(4.6.1)"],
  "example:scaling-twice": ["4.6.1", "Example 4.6.1"],
  "sec:4.6": ["4.6", "Section 4.6"],
  "sec:4.6.1": ["4.6.1", "Section 4.6.1"],
  "sec:scaling-maps": ["4.6", "Section 4.6"],
  "sec:why-counted": ["4.6.2", "Section 4.6.2"],
};

/** just the number, e.g. num("theorem:4.6") -> "4.6". */
export function num(key: NumKey): string {
  return NUMBERS[key][0];
}

/** reference text including the kind, e.g. ref("eq:5.107") -> "(5.107)". */
export function ref(key: NumKey): string {
  return NUMBERS[key][1];
}
